### ISSUE TITLE
iFrame Video not centered in Safari

### ISSUE THREAD

**Issue by emilycritter** [CodyHouse/cd-modal-video-changelog#1]
1. The video is not centered in Safari when using the iframe option. 
2. This can be seen you open the modal from the [demo (iframe)](https://codyhouse.co/ds/components/app/modal-video--iframe ) in Safari
3. Safari

Screenshot:
![image](https://user-images.githubusercontent.com/16456162/106797277-042e5a80-6622-11eb-8d65-303c68f47fa5.png)

**Comment by claudia-romano** [comment]
Hi Emily, thanks for the heads-up. 
There's an issue with the `.aspect-ratio` utility class on Safari 14. We are gonna push an updated version of the framework with this fix as soon as possible. 

Meanwhile, try adding `object-fit: fill` to the iframe element in your component css file:
```css
.aspect-ratio-16\:9 iframe {
  object-fit: fill;
} 
```

This will fix the issue. Cheers!

**Comment by emilycritter** [comment]
Thank you!

**Comment by claudia-romano** [comment]
We just released version 2.8.7 that fixes the issue. Cheers!
